export default {
    isAuthenticate: false,
    authToken: null,
    currentUser: null,
    busyBox: false,
    message: {},
    validateErrors: [],
    categories: [],
    currentCategory: {},
    services: [],
    currentService: {},
    staffs: [],
    currentStaff: {},
    latestWorkingStatus: {},
    bookingTab: 'Services',
    bookingEvent: {},
    bookingConfirm: false,
    appoints: [],
    confirmAppoint: {},
    appointedUserAppoints: [],
};
